### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by outsidercsy** [xtudbxk/DSRG-tensorflow#1]
How could I get localization_cues-cal.pickle and init.model？ @xtudbxk

**Comment by xtudbxk** [comment]
Sorry for the late reply.
You can refer to official website for DSRG (https://github.com/speedinghzl/DSRG), and download the localization_cues-cal.pickle and the init.model from the "Training the DSRG model" chapter.

**Comment by outsidercsy** [comment]
Thanks.But I find that the init.model is a caffe model file.When I directly use it in your tensorflow version code, an error turns out that the init.model can not be recognized as a tensorflow model file. Is there anything I should do with the init.model before using it?

**Comment by xtudbxk** [comment]
Yes, it is. You should use the convert.py to convert it from caffe model to npy file. And I just update the readme.md to provide the link for the converted model which you can download it directly. And for more details about the convert.py, you can refer to the project in https://github.com/xtudbxk/convert_caffemodel_to_npy .

**Comment by outsidercsy** [comment]
Get it. Thanks.

**Comment by kevinlee9** [comment]
Hi, @xtudbxk . I find layers in the init caffe model(https://github.com/speedinghzl/DSRG) is different from the one provided in your repo(https://github.com/xtudbxk/DSRG-tensorflow). 

There are some extra layers in `vgg16_deeplab_aspp.npy`, like fc6_2, fc7_2, fc8-SEC2, fc6_3, fc7_3, fc8-SEC3, fc6_4, fc7_4, fc8-SEC4, but how to get parameters of these layers? As pretrained vgg only has fc6, fc7 and fc8

**Comment by xtudbxk** [comment]
1. It seems the network in origin DSRG project also use the deeplab-aspp as the baseline network. So I think the two project has the same layers.
2. All  my pretrained model is from the [Deeplab project](http://liangchiehchen.com/projects/DeepLab.html), I just convert all of it into npy file format. You can find the convert code from  [this project](https://github.com/xtudbxk/convert_caffemodel_to_npy).
3. And what's more, during my training, I find that even without aspp strcture, the best result of dsrg also reaches 57.0% miou. So you also can remove the aspp structure, and just use the pretrained model of deeplab-largefov.

**Comment by kevinlee9** [comment]
@xtudbxk thanks, so `vgg16_deeplab_aspp.npy` is converted using this link http://liangchiehchen.com/projects/DeepLabv2_vgg.html?

**Comment by xtudbxk** [comment]
Yes, it is.
