### ISSUE TITLE
Meet Runtime Warning lead to constrain_loss:0.000000 

### ISSUE THREAD

**Issue by SkeletonOne** [xtudbxk/DSRG-tensorflow#11]
After training 250 iterations, I meet a problem of RuntimeWarning: divide by zero encountered in log

    unary = -np.log(feat)

after that, constrain_loss=0.000000, how could I colve this problem?

**Comment by xtudbxk** [comment]
In general, you can add a small positive number to pretend the feat from zero. That's says 
`unary = -np.log(feat+1e-5)` may helps.

**Comment by SkeletonOne** [comment]
Yeah that's a great idea to solve my problem. thx a lot! :)
