### ISSUE TITLE
an error

### ISSUE THREAD

**Issue by dont-know-why** [xtudbxk/DSRG-tensorflow#12]
THX  for  UR work！
but I  got an error

Traceback (most recent call last):
  File "DSRG.py", line 411, in <module>
    dsrg.train(base_lr=lr,weight_decay=5e-4,momentum=0.9,batch_size=batch_size,epoches=epoches)
  File "DSRG.py", line 371, in train
    self.saver["lr"].save(self.sess,os.path.join(self.config.get("saver_path","saver"),"lr-%f" % base_lr),global_step=i)
AttributeError: 'DSRG' object has no attribute 'saver'

**Comment by xtudbxk** [comment]
Sorry for the late reply. This saver aims to save the network when the learning rate changes. And it dosen't matter to remove it from the code. So I just suggest to remove the similar sentences in the DSRG.py.  You also could get a newer DSRG.py from github now.

**Comment by dont-know-why** [comment]
what does the input_size (321,321)mean?  Does it mean I should put images that exceed the size (321,321)into data set?
Maybe its a stupid question, but I will be so glad if u answer it .

**Comment by xtudbxk** [comment]
It's ok if you use a image smaller than (321,321). The dataset.py would resize it to (321,321) during preprocessing. Do you use your own data for this project? This input size, (321,321), is for the PASCAL VOC dataset. And if your own image is too small, maybe you should adjust this input size.
