### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Pandikk** [xtudbxk/DSRG-tensorflow#13]
Thank u for your work so much
It helps me a lot,but i have encountered an error

W tensorflow/core/framework/op_kernel.cc:1275] OP_REQUIRES failed at whole_file_read_ops.cc:114 : Not found: /data/VOCdevkit/VOC2012/JPEGImages/2008_002175.jpg; No such file or directory

 W tensorflow/core/framework/op_kernel.cc:1275] OP_REQUIRES failed at whole_file_read_ops.cc:114 : Not found: /data/VOCdevkit/VOC2012/SegmentationClassAug/2008_002175.png; No such file or directory

I don't know why the error occurs

**Comment by xtudbxk** [comment]
From the error message, it seems that you didn't have the complete dataset. You can refer to the readme.md for the link of complete datasets. And be carefully that there are two datasets you need to download.  After downloading it, just extract those two datasets into the folder "data".

**Comment by Pandikk** [comment]
Thank you for your reply.
I downloaded the data set from the address in the readme.md but the problem still exists

**Comment by xtudbxk** [comment]
Do you uncompress it ? Or you can check if the file exists manually.

**Comment by Pandikk** [comment]
Yes,i did.I can find the .jpg but can't find the .png.

**Comment by xtudbxk** [comment]
The png file is from the SBD dataset, did you download it ?

**Comment by Pandikk** [comment]
yes,i did. The two dataset are in data/

**Comment by xtudbxk** [comment]
It seems I just forgot to offer a python script to convert the mat files in SBD dataset to png format. Sorry for that, and I'll complete it and upload it in few hours. Thanks for your carefully checking.

**Comment by xtudbxk** [comment]
I just add a new python file in data folder. And now you can 'cd data' and run this script with 'python convert.py'. It would merge the two dataset into a proper format. What's more, maybe you need to install "scipy" and "scikit-image" lib first, by "pip install scipy" and "pip install scikit-image".

**Comment by Pandikk** [comment]
Thank you so much . I will try it as soon as possible

**Comment by Pandikk** [comment]
The problem has been solved！
