### ISSUE TITLE
can't download localization_cues-cal.pickle

### ISSUE THREAD

**Issue by Landmine598** [xtudbxk/DSRG-tensorflow#16]
Hi,I encountered difficulty in download this localization_cues-cal.pickle file .I can't open the CAM url in DSRG[https://github.com/speedinghzl/DSRG], because I'm in China and I can't visit Google...
Could you provide me this file maybe in the form of BaiduNetDisk?
Thank you very much!!!

**Comment by xtudbxk** [comment]
I just upload it to BaiduNetDisk. Please refer to https://pan.baidu.com/s/14a94qw4nBulqqKHLMbQGUg for the file. And the fetch code is qgig.

**Comment by Landmine598** [comment]
WOW,it's very nice of you,thank you!!!
