### ISSUE TITLE
Question about epoch

### ISSUE THREAD

**Issue by kevinlee9** [xtudbxk/DSRG-tensorflow#2]
@xtudbxk Hi, why epoch add with 300 each loop in the `train` function, is this a spell mistake?Thanks.
https://github.com/xtudbxk/DSRG-tensorflow/blob/9e5a832327c89d5bf497573086170f18f63539dc/DSRG.py#L393

**Comment by xtudbxk** [comment]
Sorry to confuse you. This sentence was  used to test if the whole network works right. And I just forget to remove it. Thanks for your careful observation.
