### ISSUE TITLE
DSRG training

### ISSUE THREAD

**Issue by karthik-sem** [xtudbxk/DSRG-tensorflow#20]
We are using Segmentation classes  of Pascal VOC to generate Augmented images which inturn is used totrain the model which means that we are using fully supervised data isn't it??So how is the model weakly supervised?Please let me know

**Comment by xtudbxk** [comment]
The complete pipeline for many recent papers can be summaried as following. At first, in the train set, we use CAM or DRFI or something else to generate some pixel-level unfaithful pseudo-labels under image-level tags supervisions. Then, those pseudo-labels are used to train the network as fully-supervised manner.  But we should keep in mind that those pixel-level pseudo-labels are unfaithful and all the information in it come from the origin image-level tags. So if you stand from a higher point, you can see that the inputs of those approach are normal images with image-level tags while the outputs are pixel-level segmentation. This is why we call it "weakly-supervised" segmentation.

**Comment by karthik-sem** [comment]
Thank You @xtudbxk .
