### ISSUE TITLE
Transfer Learning of your model

### ISSUE THREAD

**Issue by karthik-sem** [xtudbxk/DSRG-tensorflow#21]
@xtudbxk .The model is for 21 categories.Can u please suggest methods to convert it to a 2 category model?

**Comment by xtudbxk** [comment]
Sorry for the late reply. It seems there exist two things you have to do for changing it to a two categories model. The first thing is that you should change the 'category_num' in the code from 21 to 2. And the second is that you should generate the two categories' seeds by yourself.  You can use [CAM](https://github.com/ascust/SEC-MXNet) or [DRFI](https://github.com/speedinghzl/drfi_cpp) to generate the seeds.

**Comment by karthik-sem** [comment]
Thank you @xtudbxk .It is very helpful.Can u please tell what i should include in SegmentationClasses Folder for my dataset?I cannot add the mask images directly as in a sense it is fully supervised data. The Augmented images should be combination of what ?

**Comment by xtudbxk** [comment]
You should put the input images in JPEGImages folder and put the pixel-level tags in the SegmentationClassAug folder for fully supervised data. And you can refer to my code for details of paths for dataset.

**Comment by karthik-sem** [comment]
But instead of pixel level tags can we include CAM images which highlights the foreground?I want it to be completely weakly supervised without using pixel level tags.

**Comment by xtudbxk** [comment]
Of course~ You can store the generated cam dataset with the same format of "localization_cues-cal.pickle", and put it on the data folder. For the details of the format, see "pythonlib/dataset_DSRG.py".

**Comment by karthik-sem** [comment]
Thank you @xtudbxk
