### ISSUE TITLE
关于readme中附带的trained model

### ISSUE THREAD

**Issue by czzerone** [xtudbxk/DSRG-tensorflow#24]
您好，我想问下您在readme文档中附带的trained model是指已经完全训练到达到DSRG原论文中一样的效果吗？？因为我用您给的trained model和提供的用于评估的程序，跑出来的图分割效果跟DSRG论文中的分割效果不一样，所以想问一下是模型问题还是？？

**Comment by xtudbxk** [comment]
没有，我提供的是我自己训练的结果。我在readme中提到它的分割结果为0.567,与论文的0.574还有一点差距。

**Comment by czzerone** [comment]
> 没有，我提供的是我自己训练的结果。我在readme中提到它的分割结果为0.567,与论文的0.574还有一点差距。

猴滴，thx~

**Comment by czzerone** [comment]
hello，我有另一个问题想问一下，在你那个测试工程中predict.py文件中，
` if output_dir is not None:`
 `       imgio.imsave(os.path.join(output_dir,"%s_img.png"%id_),img/256.0)`
       
这样保存得到的原图感觉他的rgb通道被换了顺序一样？

**Comment by xtudbxk** [comment]
好像是的，你保存前改下吧~

**Comment by czzerone** [comment]
ok，已经改好了，thanks~
