### ISSUE TITLE
about init model

### ISSUE THREAD

**Issue by eyoujunjun** [xtudbxk/DSRG-tensorflow#28]
1.想问vgg16_deeplab_aspp.npy是从 http://liangchiehchen.com/projects/DeepLabv2_vgg.html 这个链接里面的init.caffemodel转化得到的吗，这个init.caffemodel是只使用imagenet训过的吗，因为最后一层是21分类，有一些怀疑是训练了分割任务得到的模型权重
2.想问您使用过 https://github.com/speedinghzl/DSRG 里面给的vgg16_20M_mc.caffemodel进行初始化吗
谢谢

**Comment by xtudbxk** [comment]
抱谦，现在才看到~
这个项目很久了，在我记忆中，我是使用deeplab提供的初始化权值进行初始化的，只在Imagenet上进行预训练的
