### ISSUE TITLE
Evaluation code

### ISSUE THREAD

**Issue by kevinlee9** [xtudbxk/DSRG-tensorflow#3]
Hi, @xtudbxk. Could you provide the evaluation code, thanks~

**Comment by xtudbxk** [comment]
ok, no problem. I just spend a little time to arrange the evaluation code and then put it in the [project](https://github.com/xtudbxk/semantic-segmentation-metrics). And I have to say that after I remove the fixed input size and use a multiscale input for the test. My final result has drops from 56.4% to 55.6%.

**Comment by xtudbxk** [comment]
Did that project solve your problem ? May I close this issue ?

**Comment by kevinlee9** [comment]
@xtudbxk yeah, thanks for your warm reply
