### ISSUE TITLE
test

### ISSUE THREAD

**Issue by zhenmafan7** [xtudbxk/DSRG-tensorflow#5]
hi @xtudbxk , thanks for your code,I have a question that how can I test my own image after train?

**Comment by xtudbxk** [comment]
You can referer to the [project](https://github.com/xtudbxk/semantic-segmentation-metrics) for the code to measure how good your segmentation. For your own network and dataset, maybe you should update the pythonlib/dataset.py and deeplab_aspp_test.py.
