### ISSUE TITLE
Missing checkpoint in trained_model_for_dsrg_tf.tar.gz

### ISSUE THREAD

**Issue by jsdd25** [xtudbxk/DSRG-tensorflow#8]
Hello! Your work is amazing! However, the checkpoint file is not included in the trained_model_for_dsrg_tf.tar.gz. Without it, I can not restore Tensorflow model. Could you please upload it? Thank you very much!

**Comment by xtudbxk** [comment]
Do you mean the checkpoint files generated by the trained model? You can just train this network and it will generate the checkpoint files by itself.

**Comment by jsdd25** [comment]
My computer configuration is not high and the training takes a long time. If it is convenient, could you upload it? Thank you very much!

**Comment by xtudbxk** [comment]
oh, It's OK. I just remember that I uploaded it on the github already. You can see the link on the main page of this project. Or you can download by [BaiduNetdisk](https://pan.baidu.com/s/1vITyeBR5kxaGcOF0BHGkJA).

**Comment by xtudbxk** [comment]
Oh, I see your question. And you don't need to worry about the checkpoint files. This file just goes to tell the tensorflow which one is the latest model. So just passing the "final-0" as the name of the model is ok for tensorflow.

**Comment by xtudbxk** [comment]
You can find the usage in the restroe_from_model function of https://github.com/xtudbxk/semantic-segmentation-metrics/blob/master/deeplab_aspp_test.py.

When the checkpoint is not available, just pass the "final-0" as the model_path.

**Comment by jsdd25** [comment]
@xtudbxk It's very kind of you. Thank you very much!
